force-app/main/default/objects/Aluno__c/Aluno__c.object-meta.xml
<CustomObject>
    <description>Representa os alunos de Hogwarts</description>
    <label>Aluno</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alunos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Aluno__c/fields/Casa_de_Hogwarts__c.field-meta.xml
<CustomField>
    <fullName>Casa_de_Hogwarts__c</fullName>
    <description>Representa a casa escolhida para o aluno pelo</description>
    <label>Casa de Hogwarts</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Integracao__c/Log_Integracao__c.object-meta.xml
<CustomObject>
    <label>Log de Integração</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Log de Integração Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log de Integrações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log_Integracao__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Integracao__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Consulta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Potter_Api__mdt/Potter_Api__mdt.object-meta.xml
<CustomObject>
    <label>Potter Api</label>
    <pluralLabel>Potter Api</pluralLabel>
</CustomObject>

force-app/main/default/objects/Potter_Api__mdt/fields/Character_Routes__c.field-meta.xml
<CustomField>
    <fullName>Character_Routes__c</fullName>
    <label>Character Routes</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Potter_Api__mdt/fields/House_Routes__c.field-meta.xml
<CustomField>
    <fullName>House_Routes__c</fullName>
    <label>House Routes</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Potter_Api__mdt/fields/Sorting_Hat_Route__c.field-meta.xml
<CustomField>
    <fullName>Sorting_Hat_Route__c</fullName>
    <label>Sorting Hat Route</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Potter_Api__mdt/fields/Spell_Routes__c.field-meta.xml
<CustomField>
    <fullName>Spell_Routes__c</fullName>
    <label>Spell Routes</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AlunoHelper.cls
public with sharing class AlunoHelper {
    public AlunoHelper() {}

    public static void defineCasaAluno(Map<Id, Aluno__c> newRecordsMap){
        SortingHatHouse(newRecordsMap.keySet());
    }

    @Future(callout=true)
    public static void SortingHatHouse(Set<Id> alunosId){

        List<Aluno__c> alunosToUpdate = new List<Aluno__c>();
        List<Log_Integracao__c> logsToInsert = new List<Log_Integracao__c>();

        Potter_Api__mdt potterApi = [SELECT Base_URL__c, 
                                                Character_Routes__c, 
                                                House_Routes__c, 
                                                Key__c, 
                                                Sorting_Hat_Route__c, 
                                                Spell_Routes__c
                                            FROM Potter_Api__mdt LIMIT 1];

        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(potterApi.Base_URL__c + potterApi.Sorting_Hat_Route__c);
        request.setMethod('GET');

        for(Id aId : alunosId){

            HttpResponse response = http.send(request);

            if(response.getStatusCode() == 200){

                Aluno__c aluno = new Aluno__c(Id=aId);
                aluno.Casa_de_Hogwarts__c = response.getBody().remove('"');
                alunosToUpdate.add(aluno);

                //Cria o log de integração
                logsToInsert.add(new Log_Integracao__c(Tipo__c= 'Consulta', Status__c='SUCCESS', Response__c= 'Casa sorteada: '+response.getBody().remove('"')+'\nId do aluno: '+aId));
            }
            else{
                //Cria o log de integração
                logsToInsert.add(new Log_Integracao__c(Tipo__c= 'Consulta', Status__c='FAIL', Response__c= response.getBody().remove('"')+' Id do aluno: '+aId));
            }

            if(!alunosToUpdate.isEmpty()){
                update alunosToUpdate;
            }
    
            if(!logsToInsert.isEmpty()){
                insert logsToInsert;
            }
        }
        
    }
}