force-app/main/default/objects/Aluno__c/Aluno__c.object-meta.xml
<CustomObject>
    <description>Representa os alunos de Hogwarts</description>
    <label>Aluno</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alunos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Aluno__c/fields/Casa_de_Hogwarts__c.field-meta.xml
<CustomField>
    <fullName>Casa_de_Hogwarts__c</fullName>
    <description>Representa a casa escolhida para o aluno pelo</description>
    <label>Casa de Hogwarts</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IntegrationPotterAPI.cls
@RestResource(urlMapping='/Aluno/*')
global with sharing class IntegrationPotterAPI {
    
    @HttpGet
    global static Aluno__c getAluno(){

        RestRequest request = RestContext.request;

        String alunoId = request.requestURI.substring(request.requestURI.lastIndexOf('/')+1);

        Aluno__c result =  [SELECT Id, Name, Casa_de_Hogwarts__c
                        FROM Aluno__c
                        WHERE Id = :alunoId];
        
        return result;
    }

    @HttpPost
    global static String createAluno(String nome){

        Aluno__c a = new Aluno__c(Name = nome);
        insert a;

        return a.Id;
    }
    
}