force-app/main/default/objects/Socios__c/Socios__c.object-meta.xml
<CustomObject>
    <label>Sócio</label>
    <nameField>
        <displayFormat>Socio-{00000}</displayFormat>
        <label>Sócio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sócios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Socios__c/fields/ContaAssociada__c.field-meta.xml
<CustomField>
    <fullName>ContaAssociada__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Conta Associada</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sócios</relationshipLabel>
    <relationshipName>ContaSocio</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Socios__c/fields/ContatoSocio__c.field-meta.xml
<CustomField>
    <fullName>ContatoSocio__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contato Sócio</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sócios</relationshipLabel>
    <relationshipName>Socios</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CardTestController.cls
public without sharing class CardTestController {
    
    @AuraEnabled(cacheable=true)
    public static List<Contact> getContacts(Id accountId){

        return [SELECT Id, Name, Title, Email, Phone FROM Contact WHERE AccountId =: accountId];
    }

    @AuraEnabled
    public static void createSocios(String accountId, List<String> contactsId){
        System.debug('Conta recebida: '+accountId);
        System.debug('contatos recebidos: '+contactsId);

        List<Socios__c> sociosList = new List<Socios__c>();

        for (String contact : contactsId){
            sociosList.add(new Socios__c(ContaAssociada__c = accountId, ContatoSocio__c = contact));
        }

        try{
            insert sociosList;  
        }
        catch(Exception e){
            System.debug(e.getMessage());
        }
    }
}